### ISSUE TITLE
Getting 504 Gateway Timeout Error whenever I put Sagenda Calendar on the page

### ISSUE THREAD

**Issue by alvinshaw** [Sagenda/sagenda-calendar-wp#4]
I tried removing the [sagenda-calendar-wp] code from the page. And the page loaded perfectly fine. 
But whenever I add this code I get 504 Gateway Timeout Error.
Please help to fix it. 

I'm using - 
Wordpress: 5.7.1
Theme: Beaver Builder

**Comment by IterationCorp** [comment]
Hello
Probably webservice ULR to sagenda.net/api/ is blocked on your hosting, please ask your provider. 
To get support please use only : https://iteration.atlassian.net/servicedesk/customer/portal/2 
Thanks
